### PR TITLE
Add download links to Projects

### LINKED ISSUE #157: Add download links to the projects
Add an optional new field in projects for downloading the open sorce project.

An example: 

image

I would like to make a PR which implements this, if you like the idea.

### PR DESCRIPTION
**Pull request by Aaron-Junker**
Fixes #157

Adds new optional `storeUrl` property to add link to [Windows Apps preview store](https://apps.microsoft.com/store/detail/microsoft-powertoys/XP89DCGQ3K6VLD). I choose this one, because it's accesible from every platform.

image

image

cc: @jeffwilcox @emmairwin

### CODE REVIEW

**Comment by jeffwilcox** [comment]
I love it, but we do need to think about the accessibility piece. We failed an accessibility review previously where the text was very generic, "Visit project" vs "Visit PowerShell", for example. I think it was something about a screen reading providing the most-specific and helpful content.

So as long as we take that into account, I think that's worth doing.

**Comment by Aaron-Junker** [comment]
> I love it, but we do need to think about the accessibility piece. We failed an accessibility review previously where the text was very generic, "Visit project" vs "Visit PowerShell", for example. I think it was something about a screen reading providing the most-specific and helpful content.
> 
> So as long as we take that into account, I think that's worth doing.

Would a title argument with something like `Download "projectname" from Microsoft Store` on the link be ok?

**Comment by Aaron-Junker** [comment]
Removed changes from lockfile. I first didn't get how it worked

**Comment by Aaron-Junker** [comment]
@jeffwilcox I changed the link text:

image

image

**Comment by emmairwin** [comment]
@jeffwilcox does this address your concern about accessiblity, or is there other guidance to be shared to support this PRs success?

**Comment by jeffwilcox** [comment]
Sounds good, thanks all.

**Review by jeffwilcox — APPROVED** [review]

**Pull request merged**
