### PR TITLE
dotNet foundation issue solved

### PR DESCRIPTION
**Pull request by AdityaAB4**

### CODE REVIEW

**Comment by AdityaAB4** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by AdityaAB4** [comment]
@microsoft-github-policy-service agree

**Comment by AdityaAB4** [comment]
image
Could you please take a look at this?

**Comment by emmairwin** [comment]
@AdityaAB4 sorry for the negative experience here, many of us were away and this should not have been closed, I will take a look at this this week!  Thanks for your contribution.

**Review by jeffwilcox — CHANGES_REQUESTED** [review]
Hey @AdityaAB4 - could you please submit this without any changes to the Gemfile or Gemfile.lock?

**Comment by AdityaAB4** [comment]
Yes I will try it. But is it okay if I do it after a week?

**Comment by jeffwilcox** [comment]
Thanks again for your contribution. To resolve a cookie-related issue, I was able to commit the updates needed but still give you credit for the commits and contribution. Thanks so much! Merging now.

**Review by jeffwilcox — APPROVED** [review]

**Pull request merged**
