### PR TITLE
Adding several projects, featuring CNAB

### PR DESCRIPTION
**Pull request by bureado**
Hi! In this PR I'm suggesting several open source projects from Microsoft for addition to the showcase, and promoting CNAB as a featured project in the homepage.

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Thanks Jose.

I suppose we might need to get on some more features to start rotating through projects or better visualizing all these pages...

**Comment by jeffwilcox** [comment]
FYI @crutkas Jose is taking over the PowerToys featured slot with this PR!

(One idea to make the featured capability less manual was to build either a build-time or runtime queue of which projects are featured throughout the week in some form)

**Comment by bureado** [comment]
An ideal feature would be to randomize who we render in the three featured slots. But the editorial criteria I took for my PR was to feature something dev, something cloud, something platform -- along those lines.

**Comment by ItalyPaleAle** [comment]
Here are some icons:

Bond: bond

Dapr: https://dapr.io/images/logos/dapr.svg

Fast [fast.svg.zip](https://github.com/microsoft/opensource.microsoft.com/files/5076036/fast.svg.zip)

ONNX: https://raw.githubusercontent.com/microsoft/onnxruntime/master/docs/images/ONNX_Runtime_icon.png

VFS for Git: https://vfsforgit.org/images/header.png

**Comment by jeffwilcox** [comment]
Thanks @bureado ... we actually have some JS magic for that in the blog posts, if and when we want to keep more curated there; so would be straightforward (https://github.com/microsoft/opensource.microsoft.com/blob/main/index.html#L244)

@ItalyPaleAle @bureado could one of you PR those icons if you have a chance?

**Comment by ItalyPaleAle** [comment]
I made a PR #46. Couldn't find a logo for all projects, but at least there's some

**Pull request merged**
