### PR TITLE
Calculator feature added

### PR DESCRIPTION
**Pull request by santoshmanaguli**

### CODE REVIEW

**Comment by Aaron-Junker** [comment]
Thank you for your PR. But it seems you reverted your commit.

**Comment by santoshmanaguli** [comment]
ya, some things went wrong from my side so I had to revert the commit

**Comment by santoshmanaguli** [comment]
@Aaron-Junker what should I do next? should I push again? or should I create another PR?

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker what should I do next? should I push again? or should I create another PR?

Pushing it again if this is possible.

**Comment by santoshmanaguli** [comment]
pushed.

**Pull request merged**
