### PR TITLE
header ui update on tablet

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/microsoft/opensource.microsoft.com/issues/197

### CODE REVIEW

**Comment by antoshek** [comment]
Удалите мою страницу окончательно!

Скачайте Outlook для Android<https://aka.ms/AAb9ysg>
________________________________
From: Ihor Sychevskyi ***@***.***>
Sent: Sunday, April 10, 2022 8:09:09 PM
To: microsoft/opensource.microsoft.com ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/opensource.microsoft.com] header ui update on tablet (PR #198)


resolve #197<https://github.com/microsoft/opensource.microsoft.com/issues/197>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/microsoft/opensource.microsoft.com/pull/198

Commit Summary

  *   9a6f3ec<https://github.com/microsoft/opensource.microsoft.com/pull/198/commits/9a6f3ec2c1305c71dd42dc518628da0ad40d947e> header ui update on tablet

File Changes

(2 files<https://github.com/microsoft/opensource.microsoft.com/pull/198/files>)

  *   M _dev/scss/_settings.scss<https://github.com/microsoft/opensource.microsoft.com/pull/198/files#diff-49beaad3aa6470695d071cd5ce10d8cda479adfe9c24c8edbd737cf2eb3f0d67> (2)
  *   M assets/css/index.css<https://github.com/microsoft/opensource.microsoft.com/pull/198/files#diff-e8a4c4a7e99ab11a03d712d93fb3b494b8b39a1948de1418e26c7bda977cfb9c> (2)

Patch Links:

  *   https://github.com/microsoft/opensource.microsoft.com/pull/198.patch
  *   https://github.com/microsoft/opensource.microsoft.com/pull/198.diff

**Comment by Aaron-Junker** [comment]
> Удалите мою страницу окончательно!

@emmairwin I don't know if the translation is right. But seems like a spam comment to me.

**Comment by Aaron-Junker** [comment]
@emmairwin @jeffwilcox I'm not able to  build the dockerimage anymore (for no branch). I always get this error message: 

```
> [build 6/9] RUN bundle install:
#12 0.417 Bundler 2.3.11 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
#12 1.640 Fetching gem metadata from https://rubygems.org/.
#12 1.679 Fetching bundler 2.1.4
#12 1.979 Installing bundler 2.1.4
#12 2.760 Fetching gem metadata from https://rubygems.org/.........
#12 4.111 listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is incompatible with
#12 4.111 the current version, ruby 3.1.1p18
------
executor failed running [/bin/sh -c bundle install]: exit code: 5
```

Any ideas why this happens?

**Comment by jamesiri** [comment]
Are you running this locally or in codespaces? I ran in codespaces and wasn't able to repro your issue.

Here is a snippet showing the pertinent data.
```@jamesiri ➜ /workspaces/opensource.microsoft.com (upd) $ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching public_suffix 4.0.6
Using bundler 2.2.9
Fetching colorator 1.1.0
Installing colorator 1.1.0
Installing public_suffix 4.0.6
Fetching concurrent-ruby 1.1.7
Fetching eventmachine 1.2.7
Installing concurrent-ruby 1.1.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching ffi 1.13.1
Installing ffi 1.13.1 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching rb-fsevent 0.10.4
Installing rb-fsevent 0.10.4
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching liquid 4.0.3
Installing liquid 4.0.3
Fetching mercenary 0.4.0
Installing mercenary 0.4.0
Fetching rouge 3.22.0
Installing rouge 3.22.0
Fetching safe_yaml 1.0.5
Installing safe_yaml 1.0.5
Fetching unicode-display_width 1.7.0
Installing unicode-display_width 1.7.0
Fetching mini_portile2 2.8.0
Installing mini_portile2 2.8.0
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching i18n 1.8.5
Installing i18n 1.8.5
Fetching sassc 2.4.0
Installing sassc 2.4.0 with native extensions
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching pathutil 0.16.2
Installing pathutil 0.16.2
Fetching kramdown 2.3.1
Installing kramdown 2.3.1
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching nokogiri 1.13.3 (x86_64-linux)
Installing nokogiri 1.13.3 (x86_64-linux)
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching listen 3.2.1
Installing listen 3.2.1
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching octicons 10.0.0
Installing octicons 10.0.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1```

The biggest difference is that I see you are using bundler 2.1.4 and I am using bundler 2.2.9. Try updating that if you are running locally.

**Comment by Aaron-Junker** [comment]
> Are you running this locally or in codespaces? I ran in codespaces and wasn't able to repro your issue.
> 
> Here is a snippet showing the pertinent data.
> 
> ```
> Fetching gem metadata from https://rubygems.org/.........
> Fetching public_suffix 4.0.6
> Using bundler 2.2.9
> Fetching colorator 1.1.0
> Installing colorator 1.1.0
> Installing public_suffix 4.0.6
> Fetching concurrent-ruby 1.1.7
> Fetching eventmachine 1.2.7
> Installing concurrent-ruby 1.1.7
> Installing eventmachine 1.2.7 with native extensions
> Fetching http_parser.rb 0.6.0
> Installing http_parser.rb 0.6.0 with native extensions
> Fetching ffi 1.13.1
> Installing ffi 1.13.1 with native extensions
> Fetching forwardable-extended 2.6.0
> Installing forwardable-extended 2.6.0
> Fetching rb-fsevent 0.10.4
> Installing rb-fsevent 0.10.4
> Fetching rexml 3.2.5
> Installing rexml 3.2.5
> Fetching liquid 4.0.3
> Installing liquid 4.0.3
> Fetching mercenary 0.4.0
> Installing mercenary 0.4.0
> Fetching rouge 3.22.0
> Installing rouge 3.22.0
> Fetching safe_yaml 1.0.5
> Installing safe_yaml 1.0.5
> Fetching unicode-display_width 1.7.0
> Installing unicode-display_width 1.7.0
> Fetching mini_portile2 2.8.0
> Installing mini_portile2 2.8.0
> Fetching racc 1.6.0
> Installing racc 1.6.0 with native extensions
> Fetching addressable 2.8.0
> Installing addressable 2.8.0
> Fetching i18n 1.8.5
> Installing i18n 1.8.5
> Fetching sassc 2.4.0
> Installing sassc 2.4.0 with native extensions
> Fetching rb-inotify 0.10.1
> Installing rb-inotify 0.10.1
> Fetching pathutil 0.16.2
> Installing pathutil 0.16.2
> Fetching kramdown 2.3.1
> Installing kramdown 2.3.1
> Fetching terminal-table 1.8.0
> Installing terminal-table 1.8.0
> Fetching nokogiri 1.13.3 (x86_64-linux)
> Installing nokogiri 1.13.3 (x86_64-linux)
> Fetching em-websocket 0.5.1
> Installing em-websocket 0.5.1
> Fetching listen 3.2.1
> Installing listen 3.2.1
> Fetching kramdown-parser-gfm 1.1.0
> Installing kramdown-parser-gfm 1.1.0
> Fetching octicons 10.0.0
> Installing octicons 10.0.0
> Fetching jekyll-watch 2.2.1
> Installing jekyll-watch 2.2.1```
> 
> The biggest difference is that I see you are using bundler 2.1.4 and I am using bundler 2.2.9. Try updating that if you are running locally.
> ```

@jamesiri Locally. As you can see it automatically downloads Bundler 2.1.4. I've 2.3.11 installed

**Comment by emmairwin** [comment]
Hi @Aaron-Junker I have had similar problems in the past, which one time was due to having two different versions installed on my machine and ensuring Jekyll was looking at the right one.  I would suggest if you continue to have this problem posting in forums with people who are expert with Jekyll, that's likely where you will get the quickest answer.

**Comment by Arhell** [comment]
any updates?

**Review by Aaron-Junker — CHANGES_REQUESTED** [review]
I'm very sorry for this delay. 

This PR looks good, but there is weird leftover item as shown in this screenshot:

image

Would it be possible to fix that too?

**Comment by Arhell** [comment]
> I'm very sorry for this delay.
> 
> This PR looks good, but there is weird leftover item as shown in this screenshot:
> 
> image
> 
> Would it be possible to fix that too?

Possibly in another PR

**Review by Aaron-Junker — APPROVED** [review]
LGTM then

**Comment by emmairwin** [comment]
Please see comment in #197 I need more information.

**Pull request closed without merging**
