### PR TITLE
Main page updates

### PR DESCRIPTION
**Pull request by emmairwin**
- updates to index page for add new Azure open source panel
- new open source updates, linking to  3 recent blog posts
- associated images for those blog posts

### CODE REVIEW

**Comment by jeffwilcox** [comment]
@emmairwin are the blog posts actually displaying? I thought we hid them from the main site these days

**Comment by emmairwin** [comment]
@jeffwilcox we had originally done that, but then to accommodate the short term display of 'Open Source on Azure', we re-enabled that bloc, renamed it 'Open Source Updates'.

 With the new Open Source on Azure panel, I thought why not put some recent blogs there again, but I don't feel strongly - I know its easy to get out of date.  Thoughts?

**Review by jeffwilcox — APPROVED** [review]

**Comment by Dreamypops33** [comment]
What about me

**Comment by yogiwahyuuu** [comment]
cone layout Februari 1 2023

**Pull request merged**
