### PR TITLE
accessibility update search placeholder color

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/microsoft/opensource.microsoft.com/issues/165
after fix
Screenshot_3

### CODE REVIEW

**Comment by Arhell** [comment]
cc @jeffwilcox

**Review by SMJC25 — COMMENTED** [review]
Para que sirve

**Comment by Aaron-Junker** [comment]
Hi @Arhell . Sorry for hearing nothing on your PRs. I will try to review them as quickly as possible. 

Thank you in advance for your contributions.

**Review by Aaron-Junker — APPROVED** [review]
Works as expected

**Review by Arhell — COMMENTED** [review]
update css

**Comment by Aaron-Junker** [comment]
> update css

What exactly did you update ?

**Comment by Arhell** [comment]
> > update css
> 
> What exactly did you update ?

there were conflicts, corrected

https://github.com/microsoft/opensource.microsoft.com/pull/166/files#diff-e8a4c4a7e99ab11a03d712d93fb3b494b8b39a1948de1418e26c7bda977cfb9c

**Pull request merged**
