### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by prasad-chavan1**
Added Contribute menu to footer which helps newbies to findout repository easily
- I have read all contributing guidelines

### CODE REVIEW

**Comment by prasad-chavan1** [comment]
i hope this comment finds yuh better sir

**Comment by Aaron-Junker** [comment]
Hi! Thank you for your contributions.

However the website is already linked on the top of the footer. And it is also more visible and clear then just "Contribute".

What is your opinion @jeffwilcox @emmairwin

**Comment by prasad-chavan1** [comment]
Thank you for your input, and I appreciate your perspective.
I understand that the website link is already present in the footer and is
quite visible. However, there are some valid reasons to consider adding a
"Contribute" option to the footer:

* Clarity of Intent: While the website link is clear, the "Contribute"
option explicitly communicates that visitors have an opportunity to take
action. It's a more direct way to invite users to engage with your content
or cause.

* Call to Action: "Contribute" serves as a strong call to action. It
encourages visitors to actively participate, whether it's by donating,
volunteering, or contributing in some other meaningful way. It can help
drive user engagement.

* Accessibility: Some users may have specific accessibility needs or
preferences that make a text link like "Contribute" more accessible and
easier to understand than other design elements.

* Consistency: Having a consistent and clear call to action, like
"Contribute," across different parts of your website can reinforce the
message and make it more memorable for users.

* Mobile Experience: On mobile devices, it's common for users to scroll
through the footer as they explore a website. Including a "Contribute"
option there ensures that this important call to action is always within
easy reach.


On Thu, Sep 28, 2023 at 2:52 PM Aaron Junker ***@***.***>
wrote:
Hi! Thank you for your contributions.

However the website is already linked on the top of the footer. And it is
also more visible and clear then just "Contribute".

What is your opinion @jeffwilcox @emmairwin

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

**Comment by prasad-chavan1** [comment]
I hope this reply finds yuh better sir 😄

**Comment by jeffwilcox** [comment]
Hi folks: at this time we'd like to not change the footer. Thanks.

**Pull request closed without merging**
