### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by Shiyaspmk**
Signed-off-by: Shiyaspmk <120125895+Shiyaspmk@users.noreply.github.com>

### CODE REVIEW

**Comment by Shiyaspmk** [comment]
@microsoft-github-policy-service agree [company="{shiyaspmk}"]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Shiyaspmk** [comment]
> 
> @Shiyaspmk the command you issued was incorrect. Please try again. 
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
>```
>@microsoft-github-policy-service agree

**Comment by Shiyaspmk** [comment]
> 
> @Shiyaspmk the command you issued was incorrect. Please try again. 
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```
>microsoft-github-policy-service agree company="your company"

**Comment by Dreamypops33** [comment]
I need justification of work presented in addition to the program name is null.

**Review by mudanzasIPROM — APPROVED** [review]

**Comment by Dreamypops33** [comment]
That is great

**Pull request closed without merging**
