### PR TITLE
Updates to Ecosystem Page and Foundations List

### PR DESCRIPTION
**Pull request by emmairwin**
Added OpenInfra and Apache to Foundations list, and bumped down the Contributions list to just below Azure Credits.

### CODE REVIEW

**Comment by emmairwin** [comment]
Testing this, confirm that the contributions list populates as expected.

**Comment by Aaron-Junker** [comment]
For what are the two newly added images? They aren't used anywhere.

**Comment by emmairwin** [comment]
good catch @Aaron-Junker!   I missed adding those two files, that reference those images.  Added now

**Review by Aaron-Junker — CHANGES_REQUESTED** [review]
It's not a big problem, but the infos for apache are in open-infra.md and the ones for open infra in apache.md. Just the titles are correct.

Besides this is works as expected.

**Comment by jeffwilcox** [comment]
Merging and I'll fix it up, thanks!

**Comment by jeffwilcox** [comment]
follow-up PR is https://github.com/microsoft/opensource.microsoft.com/pull/232

**Pull request merged**
