### PR TITLE
Add outreachy image

### PR DESCRIPTION
**Pull request by fossygirl**
Add outreachy image

### CODE REVIEW

**Comment by jeffwilcox** [comment]
So there already is an outreachy (lowercase) graphic in the folder; if we accept this, it'll mess up some operating systems which are case insensitive but case sensitive respecting... can you replace the existing outreachy.svg image instead?

**Review by jeffwilcox — CHANGES_REQUESTED** [review]
replace existing `outreachy.svg` file instead?

**Comment by fossygirl** [comment]
I don't know how to *replace* a file? Do I delete the existing one and then merge this pull request?

**Review by antoshek — APPROVED** [review]

**Review by antoshek — CHANGES_REQUESTED** [review]
[]()

**Pull request closed without merging**
