### PR TITLE
Fix: Update path for proper reference to Microsoft logo

### LINKED ISSUE #296: Microsoft logo refers to the wrong path on Code of Conduct FAQ page
**Describe the bug**
The path to Microsoft logo on the Code of Conduct FAQ page shows a 404 error. It is not properly referenced in the permalink.
**To Reproduce**
1. Go to [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/)
2. Check the logo on top. 

**Expected behavior**
The Microsoft logo should be displayed.

**Screenshots**
image

image

**Desktop (please complete the following information):**
 - OS: [iOS, Windows, Chrome OS and all other OS]
 - Browser [All web browsers]
 - Version [Any version]

**Smartphone (please complete the following information):**
 - Device: [Any iPhone or Android or Windows device]
 - OS: [Any compatible OS]
 - Browser [Any supported browser ]
 - Version [Any supported version]

**Additional context**
No additional info.

### PR DESCRIPTION
**Pull request by Abinashbunty**
Fixes #296

### CODE REVIEW

**Comment by Abinashbunty** [comment]
@jeffwilcox Requesting a review for this. 😄 Thanks in advance.

**Review by Aaron-Junker — CHANGES_REQUESTED** [review]
I think instead of changing the permalink (which breaks other things linking to it) you should try to fix the logo so that it always point s to the right resource.

**Comment by Abinashbunty** [comment]
@Aaron-Junker Implemented the changes. 😄

**Comment by emmairwin** [comment]
@Abinashbunty thanks so much for this, I will review this week!

**Comment by Abinashbunty** [comment]
Thanks @emmairwin 😄

**Comment by emmairwin** [comment]
Looks good to me (confirmed fixes the problem without introducing new ones)!  thank you for this @Abinashbunty

**Comment by Abinashbunty** [comment]
Thanks @emmairwin 😄

**Pull request merged**
