### PR TITLE
update footer items on tablet

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/microsoft/opensource.microsoft.com/issues/167

### CODE REVIEW

**Comment by Aaron-Junker** [comment]
Could you explain me, what exactly is changed? I don't really see a difference when testing

**Comment by Arhell** [comment]
> Could you explain me, what exactly is changed? I don't really see a difference when testing

As you can see https://github.com/microsoft/opensource.microsoft.com/issues/167
in the screenshot, the content climbs on top of each other, I corrected

**Review by Aaron-Junker — APPROVED** [review]
LGTM. Works as expected

**Comment by Arhell** [comment]
resolve conflicts
cc @emmairwin

**Comment by jeffwilcox** [comment]
Unfortunately we have merge conflicts on this one, Aaron or @Arhell would one of you be able to pull the latest `main` changes in plus this and rebuild the assets file?

We also might be able to remove the committed, built output files, and just ensure that the build process is working correctly to hydrate all these assets, removing this kind of problem in the future.

**Comment by Arhell** [comment]
@jeffwilcox done

**Comment by jeffwilcox** [comment]
Thank you.
Accepting this for now, appreciate it!

**Comment by Maybeadivorce12** [comment]
Remove

**Pull request merged**
